steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

    options:
    logging: CLOUD_LOGGING_ONLY

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'wayhaven-backend',
        '--source', '.',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]