services:
  - type: web
    name: wayhaven-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
    disk:
      name: wayhaven-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1